import { expect, test } from './test'
import { login } from './login'

test('manual Brain Lyrics Doctor loop preserves exact material and reversible experiments', async ({ page }, testInfo) => {
  testInfo.annotations.push({ type: 'environment', description: 'Local mocked auth/provider; manual flow makes no assistance requests. Browser emulation, not physical device acceptance.' })
  let providerRequests = 0
  page.on('request', request => { if (/\/api\/(generate|workspace-assist)/.test(request.url())) providerRequests++ })
  await login(page)
  await page.getByText('Choose nodes without dragging').click()
  await page.getByRole('button', { name: 'Collect Piano', exact: true }).click()
  const intent = '  Piano leads.\nKeep space for the words.  '
  await page.getByLabel('Describe your song').fill(intent)
  await page.screenshot({ path: testInfo.outputPath('workspace-creative-loop-local-mocked-auth-brain.png'), fullPage: true })
  await page.getByRole('button', { name: 'Lyrics', exact: true }).click()
  await page.getByRole('button', { name: '+ Verse', exact: true }).click()
  await page.getByLabel('Verse lyrics', { exact: true }).fill('Keep my phrase\nOld ending')
  await page.getByRole('button', { name: '+ Chorus', exact: true }).click()
  await page.getByLabel('Chorus lyrics', { exact: true }).fill('The chorus remains')
  await page.getByRole('article', { name: 'Chorus, section 2' }).getByRole('button', { name: 'Preserve section', exact: true }).click()
  await page.getByText('Keep what matters', { exact: true }).click()
  await page.getByLabel('Exact phrase to keep', { exact: true }).fill('Keep my phrase')
  await page.getByRole('button', { name: 'Preserve phrase', exact: true }).click()
  await page.screenshot({ path: testInfo.outputPath('workspace-creative-loop-local-mocked-auth-lyrics.png'), fullPage: true })
  await page.getByRole('button', { name: 'Fix', exact: true }).click()
  await page.getByRole('button', { name: 'Lyrics issue', exact: true }).click()
  await page.getByLabel('What did you hear, and what did you want instead?').fill('The verse ending felt crowded.')
  await page.getByText('Plan your own small experiment', { exact: true }).click()
  await page.getByLabel('Where would you like to try a change?').selectOption({ label: 'Verse' })
  await page.getByLabel('Your proposed revision', { exact: true }).fill('Keep my phrase\nNew ending')
  await page.getByRole('button', { name: 'Preview my experiment', exact: true }).click()
  await page.reload()
  await expect(page.getByLabel('Modify proposed revision', { exact: true })).toHaveValue('Keep my phrase\nNew ending')
  await page.screenshot({ path: testInfo.outputPath('workspace-creative-loop-local-mocked-auth-doctor.png'), fullPage: true })
  await page.getByRole('button', { name: 'Try this change', exact: true }).click()
  await page.getByRole('button', { name: 'Edit in Lyrics', exact: true }).click()
  await expect(page.getByRole('article', { name: 'Verse, section 1' })).toHaveClass(/is-highlighted/)
  await expect(page.getByLabel('Verse lyrics', { exact: true })).toHaveValue('Keep my phrase\nNew ending')
  await expect(page.getByLabel('Chorus lyrics', { exact: true })).toBeDisabled()
  await expect(page.getByLabel('Chorus lyrics', { exact: true })).toHaveValue('The chorus remains')
  await page.getByRole('button', { name: 'Revert this change', exact: true }).click()
  await expect(page.getByLabel('Verse lyrics', { exact: true })).toHaveValue('Keep my phrase\nOld ending')
  await page.getByRole('button', { name: 'Sound', exact: true }).click()
  await expect(page.getByLabel('Describe your song')).toHaveValue(intent)
  await expect(page.locator('[data-node-id="piano"]')).toHaveCount(1)
  expect(new URL(page.url()).search).toBe('')
  expect(providerRequests).toBe(0)
  await page.setViewportSize({ width: 320, height: 800 })
  for (const mode of ['Sound', 'Lyrics', 'Send to Suno', 'Fix']) {
    await page.getByRole('button', { name: mode, exact: true }).click()
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  }
})
