import { expect, test } from './test'
import { login } from './login'

test('first-use controls lead through song context preservation and a reversible mocked revision', async ({ page, request, isMobile }, info) => {
  info.annotations.push({ type: 'environment', description: 'Synthetic song; local mocked auth/provider; browser emulation, not human usability testing.' })
  await request.post('http://127.0.0.1:3132/__fixture/quota')
  await request.post('http://127.0.0.1:3132/__fixture/assistance?mode=normal')
  const activate = async (button: ReturnType<typeof page.getByRole>) => isMobile ? button.tap() : button.click()
  await login(page)
  await expect(page.getByRole('button', { name: 'Dismiss song hint' })).toBeVisible()
  const drawer = page.getByRole('button', { name: /Song drawer/ })
  const scene = await page.getByTestId('sound-brain-scene').boundingBox()
  const controls = await page.locator('.workspace-navigation').boundingBox()
  if (isMobile) {
    expect(controls!.y + controls!.height).toBeLessThanOrEqual(page.viewportSize()!.height + 1)
    await expect(page.getByRole('navigation', { name: 'Song tools' })).toHaveCount(1)
    expect(await page.locator('.workspace-navigation').evaluate(element => getComputedStyle(element).position)).toBe('fixed')
    const content = await page.getByRole('main').boundingBox()
    expect(content!.y + content!.height).toBeLessThanOrEqual(controls!.y)
  } else expect(controls!.y + controls!.height).toBeLessThanOrEqual(scene!.y)
  await page.screenshot({ path: info.outputPath('workspace-discovery-brain.png'), fullPage: !isMobile })
  await activate(drawer)
  await expect(page.getByRole('dialog', { name: 'Song drawer' })).toBeVisible()
  await page.getByText('Bring existing Styles into this song', { exact: true }).click()
  await page.getByLabel('Existing Styles output').fill('Sparse piano; editable synthetic Styles.')
  await page.screenshot({ path: info.outputPath('workspace-discovery-drawer.png') })
  await activate(page.getByRole('button', { name: 'Close song drawer' }))
  await expect(drawer).toBeFocused()
  await activate(page.getByRole('button', { name: 'Dismiss song hint' }))
  await page.getByText('Choose nodes without dragging').click()
  await page.getByRole('button', { name: 'Collect Piano', exact: true }).click()
  await page.getByLabel('Relationship notes').fill('Piano carries the melody. Keep its exact role.')
  await activate(page.getByRole('button', { name: 'Lyrics', exact: true }))
  await expect(page.getByRole('button', { name: 'Lyrics', exact: true })).toHaveAttribute('aria-current', 'page')
  await page.getByRole('button', { name: '+ Verse', exact: true }).click()
  await page.getByLabel('Verse lyrics', { exact: true }).fill('Keep this line\nOld ending')
  await page.getByRole('button', { name: '+ Chorus', exact: true }).click()
  await page.getByLabel('Chorus lyrics', { exact: true }).fill('Untouched chorus')
  await activate(page.getByRole('article', { name: 'Chorus, section 2' }).getByRole('button', { name: 'Preserve section', exact: true }))
  await expect(page.getByText('Preserved section', { exact: true })).toBeVisible()
  await expect(page.getByLabel('Chorus lyrics', { exact: true })).toBeDisabled()
  await activate(page.getByRole('button', { name: 'Preserve a phrase', exact: true }))
  await expect(page.getByLabel('Exact phrase to keep', { exact: true })).toBeFocused()
  await page.getByLabel('Exact phrase to keep', { exact: true }).fill('Keep this line')
  await page.getByRole('button', { name: 'Preserve phrase', exact: true }).click()
  await expect(page.getByText('Contains a preserved phrase', { exact: false })).toBeVisible()
  if (isMobile) {
    await page.getByText('Preserved section', { exact: true }).scrollIntoViewIfNeeded()
    await page.screenshot({ path: info.outputPath('workspace-discovery-preservation.png') })
  } else await page.locator('.lyrics-studio').screenshot({ path: info.outputPath('workspace-discovery-preservation.png') })
  await page.getByRole('button', { name: 'Dismiss preservation hint' }).click()
  await page.getByLabel('Section to revise').selectOption({ label: 'Chorus' })
  await expect(page.getByRole('button', { name: 'Suggest a section revision', exact: true })).toBeDisabled()
  await page.getByLabel('Section to revise').selectOption({ label: 'Verse' })
  await page.getByLabel('What would you like to change in this section?').fill('Change the ending only.')
  await page.getByRole('button', { name: 'Suggest a section revision', exact: true }).click()
  await expect(page.getByText('Preview · not applied', { exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Review pending changes', exact: true }).click()
  await expect(page.getByRole('region', { name: 'Song experiments' })).toBeFocused()
  if (isMobile) {
    await expect(page.locator('.brain-workspace')).toHaveCSS('--keyboard-inset', '0px')
    const content = await page.getByRole('main').boundingBox()
    const bar = await page.locator('.workspace-navigation').boundingBox()
    expect(content!.y + content!.height).toBeLessThanOrEqual(bar!.y)
    expect(bar!.y + bar!.height).toBeLessThanOrEqual(page.viewportSize()!.height + 1)
  }
  await expect(page.getByLabel('Verse lyrics', { exact: true })).toHaveValue('Keep this line\nOld ending')
  await page.getByRole('button', { name: 'Try this change', exact: true }).scrollIntoViewIfNeeded()
  await page.screenshot({ path: info.outputPath('workspace-discovery-revision.png'), fullPage: !isMobile })
  await activate(page.getByRole('button', { name: 'Try this change', exact: true }))
  await expect(page.getByText('Applied to your song · reversible', { exact: true })).toBeVisible()
  await expect(page.locator('.proposal-card.is-applied')).toBeFocused()
  await activate(page.getByRole('button', { name: 'Doctor', exact: true }))
  await activate(page.getByRole('button', { name: 'Revert this change', exact: true }))
  await expect(page.getByText('Reverted · previous text restored', { exact: true })).toBeVisible()
  await activate(page.getByRole('button', { name: 'Lyrics', exact: true }))
  await expect(page.getByLabel('Verse lyrics', { exact: true })).toHaveValue('Keep this line\nOld ending')
  await expect(page.getByLabel('Chorus lyrics', { exact: true })).toHaveValue('Untouched chorus')
  await page.getByRole('button', { name: 'Suggest a section revision', exact: true }).click()
  await page.getByRole('button', { name: 'Reject', exact: true }).click()
  await expect(page.getByText('Rejected · song unchanged', { exact: true })).toBeVisible()
  await page.reload({ waitUntil: 'domcontentloaded' })
  await expect(page.getByRole('button', { name: 'Dismiss song hint' })).toHaveCount(0)
  await expect(page.getByRole('button', { name: 'Dismiss preservation hint' })).toHaveCount(0)
  await expect(page.getByLabel('Chorus lyrics', { exact: true })).toBeDisabled()
  await expect(page.getByLabel('Verse lyrics', { exact: true })).toHaveValue('Keep this line\nOld ending')
  await page.getByRole('button', { name: 'Brain', exact: true }).click()
  await expect(page.getByLabel('Relationship notes')).toHaveValue('Piano carries the melody. Keep its exact role.')
})

test('song drawer supports keyboard escape repeat opening and narrow long-content editing', async ({ page }, info) => {
  await page.emulateMedia({ reducedMotion: 'reduce' })
  await page.setViewportSize({ width: 320, height: 568 })
  await login(page)
  await page.getByLabel('Song title').fill('A long synthetic title that still belongs to the same song')
  await page.getByLabel('Relationship notes').fill('Piano carries the melody. '.repeat(100))
  const trigger = page.getByRole('button', { name: /Song drawer/ })
  await trigger.focus(); await page.keyboard.press('Enter')
  const dialog = page.getByRole('dialog', { name: 'Song drawer' })
  await expect(dialog).toBeVisible()
  await expect(page.getByRole('button', { name: 'Close song drawer' })).toBeFocused()
  await page.keyboard.press('Shift+Tab')
  expect(await dialog.evaluate(element => element.contains(document.activeElement))).toBe(true)
  await page.keyboard.press('Escape')
  await expect(dialog).not.toBeVisible(); await expect(trigger).toBeFocused()
  await page.keyboard.press('Enter')
  await page.getByText('Bring existing Styles into this song', { exact: true }).click()
  const styles = page.getByLabel('Existing Styles output')
  await styles.fill('Long content remains editable. '.repeat(100))
  // Reduced viewport approximates the available space above an on-screen keyboard.
  await page.setViewportSize({ width: 320, height: 360 })
  await styles.focus(); await styles.scrollIntoViewIfNeeded()
  expect(await dialog.evaluate(element => element.scrollWidth <= element.clientWidth + 1)).toBe(true)
  await page.keyboard.press('Escape')
  await expect(trigger).toBeFocused()
  await page.keyboard.press('Enter')
  await expect(styles).toHaveValue('Long content remains editable. '.repeat(100))
  await page.getByRole('button', { name: 'Close song drawer' }).click()
  await page.setViewportSize({ width: 320, height: 568 })
  await expect(page.getByLabel('Relationship notes')).toHaveValue('Piano carries the melody. '.repeat(100))
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  await page.screenshot({ path: info.outputPath('workspace-discovery-narrow.png') })
})
