import type { APIRequestContext, Page } from '@playwright/test'
import { expect, test } from './test'
import { login } from './login'

const fixture = 'http://127.0.0.1:3132'
const original = 'Keep this line\nOld ending'
const changed = 'Keep this line\nNew ending'
const notes = '  Piano leads.\nLeave room for the vocal.  '
const stats = async (request: APIRequestContext) => (await request.get(`${fixture}/__fixture/stats`)).json()
const mode = (request: APIRequestContext, value: string) => request.post(`${fixture}/__fixture/assistance?mode=${value}`)
const suggest = (page: Page) => page.getByRole('button', { name: 'Suggest a section revision', exact: true })
const pending = (page: Page) => page.getByRole('button', { name: /Considering your song/ })

async function seed(page: Page) {
  await login(page)
  await page.getByText('Choose nodes without dragging').click()
  await page.getByRole('button', { name: 'Collect Piano', exact: true }).click()
  await page.getByLabel('Relationship notes').fill(notes)
  await page.getByRole('button', { name: 'Lyrics', exact: true }).click()
  await page.getByRole('button', { name: '+ Verse', exact: true }).click()
  await page.getByLabel('Verse lyrics', { exact: true }).fill(original)
  await page.getByRole('button', { name: '+ Chorus', exact: true }).click()
  await page.getByLabel('Chorus lyrics', { exact: true }).fill('Untouched chorus')
  await page.getByRole('article', { name: 'Chorus, section 2' }).getByRole('button', { name: 'Preserve section', exact: true }).click()
  await page.getByText('Keep what matters', { exact: true }).click()
  await page.getByLabel('Exact phrase to keep', { exact: true }).fill('Keep this line')
  await page.getByRole('button', { name: 'Preserve phrase', exact: true }).click()
  await page.getByLabel('What would you like to change in this section?').fill('Rewrite only the ending; retain the preserved line.')
}

test.beforeEach(async ({ request }) => {
  await request.post(`${fixture}/__fixture/quota`)
  await mode(request, 'normal')
})
test.afterEach(async ({ page, request }) => {
  await page.goto('about:blank', { waitUntil: 'commit', timeout: 10_000 })
  await mode(request, 'normal')
  await request.post(`${fixture}/__fixture/quota`)
  await request.post(`${fixture}/__fixture/account`)
})

test('enabled mocked assistance preserves lyrics and supports reject apply revert across tools', async ({ page, request }, testInfo) => {
  testInfo.annotations.push({ type: 'environment', description: 'Synthetic content, local mocked auth and provider. No live AI or physical-device acceptance.' })
  await seed(page)
  const before = await stats(request)
  await page.getByLabel('Section to revise').selectOption({ label: 'Chorus' })
  await expect(suggest(page)).toBeDisabled()
  await expect(page.getByText(/This section is preserved. Choose an unlocked section/)).toBeVisible()
  expect((await stats(request)).assistanceCalls).toBe(before.assistanceCalls)
  await page.getByLabel('Section to revise').selectOption({ label: 'Verse' })
  await mode(request, 'hold')
  // Two immediate submissions must share the synchronous in-flight guard.
  await suggest(page).evaluate(button => { (button as HTMLButtonElement).click(); (button as HTMLButtonElement).click() })
  await expect(pending(page)).toBeDisabled()
  await expect.poll(async () => (await stats(request)).pendingAssistance).toBe(1)
  expect((await stats(request)).assistanceCalls).toBe(before.assistanceCalls + 1)
  await page.screenshot({ path: testInfo.outputPath('workspace-ai-local-mock-lyrics-loading.png'), fullPage: true })
  await mode(request, 'release')
  await expect(page.getByLabel('Modify proposed revision')).toHaveValue(changed)
  await expect(page.getByLabel('Verse lyrics', { exact: true })).toHaveValue(original)
  const sent = (await stats(request)).lastIntent
  expect(sent.nodes).toEqual([{ node_id: 'piano', label: 'Piano', category: 'Instrument' }])
  expect(sent.relationship_notes).toBe(notes)
  expect(sent.preservationGoals.some((goal: { scope: string; text: string }) => goal.scope === 'phrase' && goal.text === 'Keep this line')).toBe(true)
  await page.getByRole('button', { name: 'Reject', exact: true }).click()
  await expect(page.getByLabel('Verse lyrics', { exact: true })).toHaveValue(original)
  await suggest(page).click()
  await expect(page.getByLabel('Modify proposed revision')).toHaveValue(changed)
  await page.screenshot({ path: testInfo.outputPath('workspace-ai-local-mock-lyrics-proposal.png'), fullPage: true })
  await page.getByRole('button', { name: 'Try this change', exact: true }).click()
  await expect(page.getByLabel('Verse lyrics', { exact: true })).toHaveValue(changed)
  await expect(page.getByLabel('Chorus lyrics', { exact: true })).toHaveValue('Untouched chorus')
  await expect(page.getByLabel('Chorus lyrics', { exact: true })).toBeDisabled()
  await page.getByRole('button', { name: 'Doctor', exact: true }).click()
  await page.getByRole('button', { name: 'Revert this change', exact: true }).click()
  await page.getByRole('button', { name: 'Lyrics', exact: true }).click()
  await expect(page.getByLabel('Verse lyrics', { exact: true })).toHaveValue(original)
  await page.getByRole('button', { name: 'Doctor', exact: true }).click()
  await page.getByRole('button', { name: 'Missing instrument', exact: true }).click()
  await page.getByLabel('What did you hear, and what did you want instead?').fill('The cello answer was inaudible.')
  await page.getByRole('button', { name: 'Ask Doctor for a small experiment' }).click()
  await expect(page.getByLabel('Modify proposed revision')).toHaveValue(`${notes}\nCello answers the vocal.`)
  await expect(page.getByRole('heading', { name: 'Observations from this request' })).toBeVisible()
  await expect(page.getByRole('heading', { name: 'Possible issues to test' })).toBeVisible()
  await page.screenshot({ path: testInfo.outputPath('workspace-ai-local-mock-doctor-proposal.png'), fullPage: true })
  await page.getByRole('button', { name: 'Try this change', exact: true }).click()
  await page.getByRole('button', { name: 'Open in Brain', exact: true }).click()
  await expect(page.getByLabel('Relationship notes')).toHaveValue(`${notes}\nCello answers the vocal.`)
  await expect(page.locator('[data-node-id="piano"]')).toHaveCount(1)
  await page.screenshot({ path: testInfo.outputPath('workspace-ai-local-mock-brain-applied.png'), fullPage: true })
  await page.getByRole('button', { name: 'Revert this change', exact: true }).click()
  await expect(page.getByLabel('Relationship notes')).toHaveValue(notes)
  await page.reload()
  await expect(page.getByLabel('Relationship notes')).toHaveValue(notes)
  expect(new URL(page.url()).search).toBe('')
  expect((await stats(request)).assistanceCalls).toBe(before.assistanceCalls + 3)
  expect((await stats(request)).quotaUsed).toBe(3)
})

test('enabled assistance rejects provider failures malformed data quota and expired auth without changing lyrics', async ({ page, request }) => {
  await seed(page)
  const before = await stats(request)
  for (const failure of ['error', 'malformed']) {
    await mode(request, failure)
    const response = page.waitForResponse('**/api/workspace-assist')
    await suggest(page).click()
    expect((await response).status()).toBe(502)
    await expect(page.getByText('Assistance could not complete. Your song is unchanged.')).toBeVisible()
    await expect(page.getByLabel('Verse lyrics', { exact: true })).toHaveValue(original)
    await expect(page.getByLabel('Modify proposed revision')).toHaveCount(0)
  }
  expect((await stats(request)).assistanceCalls).toBe(before.assistanceCalls + 2)
  expect((await stats(request)).quotaUsed).toBe(2)
  await mode(request, 'normal')
  await request.post(`${fixture}/__fixture/quota?limit=0`)
  const quotaResponse = page.waitForResponse('**/api/workspace-assist')
  await suggest(page).click()
  expect((await quotaResponse).status()).toBe(429)
  await expect(page.getByText(/Assistance usage limit reached/)).toBeVisible()
  await request.post(`${fixture}/__fixture/revoke`)
  const authResponse = page.waitForResponse('**/api/workspace-assist')
  await suggest(page).click()
  expect((await authResponse).status()).toBe(401)
  await expect(page.getByText(/Your session has expired. Export your song, then sign in again/)).toBeVisible()
  await expect(page.getByLabel('Verse lyrics', { exact: true })).toHaveValue(original)
  await expect(page.getByLabel('Modify proposed revision')).toHaveCount(0)
  expect((await stats(request)).assistanceCalls).toBe(before.assistanceCalls + 2)
})

test('real SDK assistance timeout retains its single reservation and authored work', async ({ page, request }) => {
  await seed(page)
  await mode(request, 'timeout')
  const before = await stats(request)
  const response = page.waitForResponse('**/api/workspace-assist', { timeout: 40_000 })
  await suggest(page).click()
  await expect(pending(page)).toBeDisabled()
  expect((await response).status()).toBe(502)
  await expect(page.getByText('Assistance could not complete. Your song is unchanged.')).toBeVisible()
  await expect(page.getByLabel('Verse lyrics', { exact: true })).toHaveValue(original)
  await expect(page.getByLabel('Modify proposed revision')).toHaveCount(0)
  expect((await stats(request)).assistanceCalls).toBe(before.assistanceCalls + 1)
  expect((await stats(request)).quotaUsed).toBe(1)
})

test('late assistance cannot apply after edits navigation or an account change', async ({ page, request }) => {
  await seed(page)
  await mode(request, 'hold')
  await suggest(page).click()
  await expect.poll(async () => (await stats(request)).pendingAssistance).toBe(1)
  await page.getByLabel('Verse lyrics', { exact: true }).fill('Keep this line\nMy newer ending')
  await mode(request, 'release')
  await expect(page.getByText(/Your song changed while assistance was working/)).toBeVisible()
  await expect(page.getByLabel('Modify proposed revision')).toHaveCount(0)
  await page.getByLabel('Verse lyrics', { exact: true }).fill(original)
  await mode(request, 'hold')
  await suggest(page).click()
  await expect.poll(async () => (await stats(request)).pendingAssistance).toBe(1)
  await page.getByRole('button', { name: 'Doctor', exact: true }).click()
  await mode(request, 'release')
  await page.getByRole('button', { name: 'Lyrics', exact: true }).click()
  await expect(page.getByLabel('Verse lyrics', { exact: true })).toHaveValue(original)
  await expect(page.getByLabel('Modify proposed revision')).toHaveCount(0)
  await mode(request, 'hold')
  await suggest(page).click()
  await expect.poll(async () => (await stats(request)).pendingAssistance).toBe(1)
  await page.getByRole('button', { name: 'Sign Out', exact: true }).click()
  await expect(page).toHaveURL(/\/login$/)
  await request.post(`${fixture}/__fixture/account?second=1`)
  await login(page)
  await mode(request, 'release')
  await expect(page.getByLabel('Relationship notes')).toHaveValue('')
  await expect(page.locator('[data-node-id="piano"]')).toHaveCount(0)
  await page.getByRole('button', { name: 'Lyrics', exact: true }).click()
  await expect(page.getByLabel('Verse lyrics', { exact: true })).toHaveCount(0)
  await expect(page.getByLabel('Modify proposed revision')).toHaveCount(0)
})
